wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv
dropout_rate:
  value: 0.5
early_stopping:
  value: false
embedding_dim:
  value: 32
epochs:
  value: 200
learning_rate:
  value: 0.001
scheduler:
  value: false
transformer_heads:
  value: 2
transformer_layers:
  value: 2
