wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv
dropout_rate:
  value: 0.1
early_stopping:
  value: false
embedding_dim:
  value: 8
epochs:
  value: 250
learning_rate:
  value: 0.0005
scheduler:
  value: false
transformer_heads:
  value: 4
transformer_layers:
  value: 3
