wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv
dropout_rate:
  value: 0.5
early_stopping:
  value: true
embedding_dim:
  value: 16
epochs:
  value: 250
learning_rate:
  value: 0.0001
scheduler:
  value: true
transformer_heads:
  value: 4
transformer_layers:
  value: 4
