version: '3.8'

services:
  fastapi:
    build:
      context: ./app   # 콜론(:) 빠졌었음
    container_name: fp_ai-container
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:   # volume -> volumes (복수형)
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi