wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250409_214033.csv
dropout_rate:
  value: 0.1
early_stopping:
  value: true
embedding_dim:
  value: 8
epochs:
  value: 250
learning_rate:
  value: 0.0005
scheduler:
  value: true
transformer_heads:
  value: 2
transformer_layers:
  value: 4
