wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/train_dataset_augmented_selective_1.0.csv
dropout_rate:
  value: 0.3
early_stopping:
  value: false
embedding_dim:
  value: 32
epochs:
  value: 250
learning_rate:
  value: 0.0005
scheduler:
  value: true
transformer_heads:
  value: 2
transformer_layers:
  value: 3
