wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/merged/wifi_rssi_log_merged_20250404_002616.csv
dropout_rate:
  value: 0.3
early_stopping:
  value: true
embedding_dim:
  value: 8
epochs:
  value: 250
learning_rate:
  value: 0.0001
scheduler:
  value: false
transformer_heads:
  value: 8
transformer_layers:
  value: 4
