wandb_version: 1

batch_size:
  value: 4
data_path:
  value: ./finger_printing/datasets/merged/wifi_rssi_log_merged_20250404_002616.csv
dropout_rate:
  value: 0.1
early_stopping:
  value: true
embedding_dim:
  value: 16
epochs:
  value: 250
learning_rate:
  value: 0.001
scheduler:
  value: false
transformer_heads:
  value: 2
transformer_layers:
  value: 2
