wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv
early_stopping:
  value: false
embedding_dim:
  value: 32
epochs:
  value: 100
learning_rate:
  value: 0.0005
num_transformer_layers:
  value: 3
scheduler:
  value: false
