wandb_version: 1

batch_size:
  value: 4
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv
early_stopping:
  value: true
embedding_dim:
  value: 8
epochs:
  value: 100
learning_rate:
  value: 0.001
num_transformer_layers:
  value: 4
scheduler:
  value: false
