batch_size: 8
data_path: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250413_000254.csv
dropout_rate: 0.3
early_stopping: true
embedding_dim: 8
epochs: 250
learning_rate: 0.001
num_ap: 100
num_classes: 262
num_mac: 954
scheduler: true
transformer_heads: 4
transformer_layers: 3
