batch_size: 8
data_path: ./finger_printing/datasets/filtered_dataset_3.0.csv
dropout_rate: 0.3
early_stopping: false
embedding_dim: 32
epochs: 250
learning_rate: 0.0005
num_ap: 100
num_classes: 329
num_mac: 1201
scheduler: true
transformer_heads: 2
transformer_layers: 3
