batch_size: 4
data_path: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250413_000254.csv
dropout_rate: 0.3
early_stopping: true
embedding_dim: 16
epochs: 150
learning_rate: 0.0001
num_ap: 100
num_classes: 262
num_mac: 954
scheduler: true
transformer_heads: 4
transformer_layers: 4
