batch_size: 8
data_path: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250413_000254.csv
dropout_rate: 0.1
early_stopping: false
embedding_dim: 8
epochs: 200
learning_rate: 0.0005
num_ap: 100
num_classes: 262
num_mac: 954
scheduler: true
transformer_heads: 4
transformer_layers: 2
