# method: random
# metric:
#   name: Val Acc
#   goal: maximize

# parameters:
#   embedding_dim:
#     values: [8, 16, 32]
#   transformer_heads:
#     values: [2, 4, 8]
#   transformer_layers:
#     values: [2, 3, 4]
#   dropout_rate:
#     values: [0.1, 0.3]

#   batch_size:
#     values: [4, 8]
#   learning_rate:
#     values: [0.001, 0.0005, 0.0001]
#   epochs:
#     values: [100, 150, 200, 250, 300]
#   scheduler:
#     values: [true, false]
#   early_stopping:
#     values: [true, false]
#   data_path:
#     value: ./finger_printing/datasets/train_dataset_augmented.csv

method: random
metric:
  name: Val Acc
  goal: maximize

parameters:
  embedding_dim:
    values: [32]
  transformer_heads:
    values: [2]
  transformer_layers:
    values: [3]
  dropout_rate:
    values: [0.3]

  batch_size:
    values: [8]
  learning_rate:
    values: [0.0005]
  epochs:
    values: [250]
  scheduler:
    values: [true]
  early_stopping:
    values: [false]
  data_path:
    value: ./finger_printing/datasets/filterd_dataset_3.0.csv