wandb_version: 1

batch_size:
  value: 4
data_path:
  value: ./finger_printing/datasets/dataset_augmented.csv
dropout_rate:
  value: 0.1
early_stopping:
  value: true
embedding_dim:
  value: 8
epochs:
  value: 100
learning_rate:
  value: 0.0001
scheduler:
  value: true
transformer_heads:
  value: 8
transformer_layers:
  value: 3
