wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv
dropout_rate:
  value: 0.3
early_stopping:
  value: true
embedding_dim:
  value: 32
epochs:
  value: 150
learning_rate:
  value: 0.001
scheduler:
  value: false
transformer_heads:
  value: 8
transformer_layers:
  value: 4
