_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 4
data_path:
    value: ./finger_printing/datasets/dataset_augmented.csv
dropout_rate:
    value: 0.1
early_stopping:
    value: false
embedding_dim:
    value: 8
epochs:
    value: 300
learning_rate:
    value: 0.001
scheduler:
    value: false
transformer_heads:
    value: 8
transformer_layers:
    value: 2
