wandb_version: 1

batch_size:
  value: 8
data_path:
  value: ./finger_printing/datasets/train_dataset_augmented.csv
dropout_rate:
  value: 0.1
early_stopping:
  value: false
embedding_dim:
  value: 32
epochs:
  value: 200
learning_rate:
  value: 0.0005
scheduler:
  value: false
transformer_heads:
  value: 8
transformer_layers:
  value: 2
